[tool.poetry]
name = "dsci524_grp16_python"
version = "0.1.0"
description = ""
authors = ["Shivam Verma <vermashivam679@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
